baseURL = 'https://willhack.top'
theme = "blowfish"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 5
buildDrafts = false
buildFuture = false
enableEmoji = true
googleAnalytics = "G-7SL7HVPDGL"

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
  
  [languages.pl]
    contentDir = "content/pl"
    weight = 2
  
  [languages.de]
    contentDir = "content/de"
    weight = 3
  
  [languages.es]
    contentDir = "content/es"
    weight = 4

[pagination]
pagerSize = 10

[imaging]
anchor = "Center"

[taxonomies]
  [taxonomies.en]
    tag = "tags"
    category = "categories"
    author = "authors"
    series = "series"
  
  [taxonomies.pl]
    tag = "tagi"
    category = "kategorie"
    author = "autorzy"
    series = "serie"
  
  [taxonomies.de]
    tag = "schlagwörter"
    category = "kategorien"
    author = "autoren"
    series = "serien"
  
  [taxonomies.es]
    tag = "etiquetas"
    category = "categorías"
    author = "autores"
    series = "series"

[sitemap]
changefreq = "always"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[services]
  [services.disqus]
    shortname = 'willhack-1'

[related]
threshold = 0
toLower = false
indices = [ { name = "tags", weight = 100 }, { name = "categories", weight = 100 }, { name = "series", weight = 50 }, { name = "authors", weight = 20 }, { name = "date", weight = 10 }, { applyFilter = false, name = "fragmentrefs", type = "fragments", weight = 10 } ]
