disabled = false
languageCode = "zh-CN"
languageName = "简体中文"
weight = 5
title = "WillHack"

[services]
  [services.disqus]
    shortname = "willhack-zn"

[params]
displayName = "简体中文"
isoCode = "zh-CN"
rtl = false
dateFormat = "2006年1月2日"
logo = "logo.png"
description = "创造你的现实"

[params.author]
name = "Willhack"
email = "ml@willhack.top"
image = "img/fav.png"
headline = "创造你的现实 - 如果你想在未来的智能爆炸世界中找到自己的位置 - 现在就开始准备。"
bio = "admin"
