disabled = false
languageCode = "es"
languageName = "Espa침ol"
weight = 3
title = "WillHack"

[params]
contentDir = "content/es"
displayName = "Espa침ol"
isoCode = "es"
rtl = false
dateFormat = "2 January 2006"
logo = "logo.png"
description = "Hackea tu realidad"

[params.author]
name = "Willhack"
  email = "ml@willhack.top"
  image = "img/fav.png"
headline = "Hackea tu realidad: si quieres encontrarte en el mundo de la explosi칩n de inteligencia del ma침ana, empieza a prepararte hoy mismo."
bio = "admin"

[services]
  [services.disqus]
    shortname = "willhack-es"