disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "WillHack"

[services]
  [services.disqus]
    shortname = "willhack-1"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo.png"
description = "WillHack is your comprehensive guide to navigating the future of technology. Start preparing today for tomorrow's intelligence explosion."
keywords = ["AI", "Blockchain", "Geopolitics", "Health", "Technology", "Future", "Innovation", "Intelligence Explosion"]

[params.author]
name = "Willhack"
  email = "ml@willhack.top"
  image = "img/fav.png"
headline = "Hack you reality - If you want to find yourself in tomorrow's world of intelligence explosion - start getting ready today."
bio = "Technology expert focused on AI, blockchain, and future innovations"