disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "WillHack"

[services]
  [services.disqus]
    shortname = "willhack-1"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo.png"
description = "Hack your reality"

[params.author]
name = "Willhack"
  email = "ml@willhack.top"
  image = "img/fav.png"
headline = "Hack you reality - if you want to find yourself in tomorrow's world of intelligence explosion - start getting ready today."
bio = "admin"