disabled = false
languageCode = "pl"
languageName = "Polski"
weight = 2
title = "WillHack - Hakuj swoją rzeczywistość"

[services]
  [services.disqus]
    shortname = "willhack-pl"

[params]
displayName = "Polski"
isoCode = "pl"
rtl = false
dateFormat = "2 January 2006"
logo = "logo.png"
description = "WillHack to Twój kompleksowy przewodnik po przyszłości technologii. Zacznij przygotowywać się już dziś na nadchodzącą eksplozję inteligencji."
keywords = ["Sztuczna Inteligencja", "Blockchain", "Geopolityka", "Zdrowie", "Technologia", "Przyszłość", "Innowacje", "Eksplozja Inteligencji"]

[params.author]
name = "Willhack"
  email = "ml@willhack.top"
  image = "img/fav.png"
headline = "Jeśli chcesz odnaleźć się w jutrzejszym świecie eksplozji inteligencji - zacznij przygotowywać się już dziś."
bio = "Ekspert technologiczny specjalizujący się w AI, blockchain i innowacjach przyszłości"
