disabled = false
languageCode = "es"
languageName = "Español"
weight = 3
title = "WillHack"

[params]
displayName = "ES"
isoCode = "es"
rtl = false
dateFormat = "2 January 2006"
logo = "logo.png"
description = "Hackea tu realidad"

[params.author]
headline = "Hackea tu realidad: si quieres encontrarte en el mundo de la explosión de inteligencia del mañana, empieza a prepararte hoy mismo."
bio = "admin"
