
[[main]]
name = "Über mich"
pageRef = "Aboutme"
weight = 1

[[main]]
name = "KI"
pageRef = "AI"
weight = 2

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
weight = 3

[[main]]
name = "Technologie"
pageRef = "Technology"
weight = 4

[[main]]
name = "Gesundheit"
pre = "heart"
pageRef = "Health"
weight = 5

[[main]]
name = "Geopolitik"
pageRef = "Geopolitics"
weight = 6

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "/tags"
weight = 10

[[footer]]
name = "Kategorien"
pageRef = "categories"
weight = 20

[[footer]]
   name = "Autoren"
   pageRef = "authors"
   weight = 30
