[[main]]
none = "none"

[[main]]
name = "Sobre mí"
pageRef = "Sobremi"
identifier = "aBce1739Ef"
weight = 1

[[main]]
name = "IA"
pageRef = "IA"
identifier = "QwEr1234Ty"
weight = 2

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
identifier = "UiOp5678As"
weight = 3

[[main]]
name = "Tecnología"
pageRef = "Tecnología"
identifier = "DfGh9012Jk"
weight = 4

[[main]]
name = "Salud"
pre = "heart"
pageRef = "Salud"
identifier = "LzXc3456Vb"
weight = 5

[[main]]
name = "Geopolítica"
pageRef = "Geopolítica"
identifier = "NmQw7890Rt"
weight = 6

[[footer]]
none = "none"

[[footer]]
name = "etiquetas"
pageRef = "tags"
identifier = "YuIo1234Pp"
weight = 9999

[[footer]]
name = "categorías"
pageRef = "categories"
identifier = "AaSs5678Dd"
weight = 9999
