[[main]]
none = "none"

[[main]]
name = "KI"
pageRef = "KI"
identifier = "FfGg1234Hh"
weight = 1

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
identifier = "IiJj5678Kk"
weight = 2

[[main]]
name = "Technologie"
pageRef = "Technologie"
identifier = "LlMm9012Nn"
weight = 3

[[main]]
name = "Gesundheit"
pre = "heart"
pageRef = "Gesundheit"
identifier = "OoPp3456Qq"
weight = 4

[[main]]
name = "Geopolitik"
pageRef = "Geopolitik"
identifier = "RrSs7890Tt"
weight = 5

[[footer]]
none = "none"

[[footer]]
name = "tags"
pageRef = "tags"
identifier = "UuVv1234Ww"
weight = 9999

[[footer]]
name = "kategorien"
pageRef = "categories"
identifier = "XxYy5678Zz"
weight = 9999
