
[[main]]
name = "Über mich"
pageRef = "Aboutme"
weight = 1

[[main]]
name = "Projekte"
pageRef = "Projects"
weight = 2

      [[main]]
      name = "Persönliche Agenten"
      parent = "Projekte"
      pageRef = "PersonalAgents"
      weight = 21

      [[main]]
      name = "Handelsvertreter"
      parent = "Projekte"
      pageRef = "BusinessAgents"
      weight = 22



[[main]]
name = "KI"
pageRef = "AI"
weight = 3

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
weight = 4

[[main]]
name = "Technologie"
pageRef = "Technology"
weight = 5

[[main]]
name = "Gesundheit"
pre = "heart"
pageRef = "Health"
weight = 6

[[main]]
name = "Geopolitik"
pageRef = "Geopolitics"
weight = 7

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "/tags"
weight = 10

[[footer]]
name = "Kategorien"
pageRef = "categories"
weight = 20

[[footer]]
   name = "Autoren"
   pageRef = "authors"
   weight = 30
