[[main]]
name = "O mnie"
pageRef = "Aboutme"
weight = 1

[[main]]
name = "Projekty"
pageRef = "Projects"
weight = 2

      [[main]]
      name = "Agenci osobiści"
      parent = "Projekty"
      pageRef = "PersonalAgents"
      weight = 21

      [[main]]
      name = "Agenci biznesowi"
      parent = "Projekty"
      pageRef = "BusinessAgents"
      weight = 22

[[main]]
name = "AI"
pageRef = "AI"
weight = 3

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
weight = 4

[[main]]
name = "Technologia"
pageRef = "Technology"
weight = 5

[[main]]
name = "Zdrowie"
pre = "heart"
pageRef = "Health"
weight = 6

      [[main]]
      name = "Konwencjonalnie"
      parent = "Zdrowie"
      pageRef = "conventionally"
      weight = 23

      [[main]]
      name = "Niekonwencjonalnie"
      parent = "Zdrowie"
      pageRef = "unconventionally"
      weight = 24

[[main]]
name = "Geopolityka"
pageRef = "Geopolitics"
weight = 7

[[footer]]
none = "none"

[[footer]]
name = "Tagi"
pageRef = "tags"
weight = 10

[[footer]]
name = "Kategorie"
pageRef = "categories"
weight = 20

[[footer]]
   name = "Autorzy"
   pageRef = "authors"
   weight = 30