
[[main]]
name = "Sobre mí"
pageRef = "Aboutme"
weight = 1

[[main]]
name = "Proyectos"
pageRef = "Projects"
weight = 2

    [[main]]
      name = "Agentes personales"
      parent = "Proyectos"
      pageRef = "PersonalAgents"
      weight = 21

      [[main]]
      name = "Agentes comerciales"
      parent = "Proyectos"
      pageRef = "BusinessAgents"
      weight = 22

[[main]]
name = "AI"
pageRef = "AI"
weight = 3

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
weight = 4

[[main]]
name = "Tecnología"
pageRef = "Technology"
weight = 5

[[main]]
name = "Salud"
pre = "heart"
pageRef = "Health"
weight = 6

  [[main]]
      name = "Convencionalmente"
      parent = "Salud"
      pageRef = "conventionally"
      weight = 23

      [[main]]
      name = "Unconventionally"
      parent = "Salud"
      pageRef = "unconventionally"
      weight = 24

[[main]]
name = "Geopolítica"
pageRef = "Geopolitics"
weight = 7

[[footer]]
name = "Tags"
pageRef = "tags"

weight = 10

[[footer]]
name = "Categorías"
pageRef = "categories"
weight = 20

[[footer]]
   name = "Autores"
   pageRef = "authors"
   weight = 30

[[footer]]
name = "archivo"
pageRef = "archives"
weight = 40