
[[main]]
name = "About me"
pageRef = "Aboutme"
weight = 1

[[main]]
name = "AI"
pageRef = "AI"
weight = 2

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
weight = 3

[[main]]
name = "Technology"
pageRef = "Technology"
weight = 4

[[main]]
name = "Health"
pre = "heart"
pageRef = "Health"
weight = 5

[[main]]
name = "Geopolitics"
pageRef = "Geopolitics"
weight = 6

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "tags"

weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20

[[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 30
