
[[main]]
name = "About me"
pageRef = "Aboutme"
weight = 1

[[main]]
name = "Projects"
pageRef = "Projects"
weight = 2

      [[main]]
      name = "Personal Agents"
      parent = "Projects"
      pageRef = "PersonalAgents"
      weight = 21

      [[main]]
      name = "Business Agents"
      parent = "Projects"
      pageRef = "BusinessAgents"
      weight = 22

[[main]]
name = "AI"
pageRef = "AI"
weight = 3

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
weight = 4

[[main]]
name = "Technology"
pageRef = "Technology"
weight = 5

[[main]]
name = "Health"
pre = "heart"
pageRef = "Health"
weight = 6

[[main]]
name = "Geopolitics"
pageRef = "Geopolitics"
weight = 7

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "tags"

weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20

[[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 30

[[footer]]
name = "archives"
pageRef = "archives"
weight = 40
