
[[main]]
name = "Sobre mí"
pageRef = "Aboutme"
weight = 1

[[main]]
name = "AI"
pageRef = "AI"
weight = 2

[[main]]
name = "Blockchain"
pageRef = "Blockchain"
weight = 3

[[main]]
name = "Tecnología"
pageRef = "Technology"
weight = 4

[[main]]
name = "Salud"
pre = "heart"
pageRef = "Health"
weight = 5

[[main]]
name = "Geopolítica"
pageRef = "Geopolitics"
weight = 6

[[footer]]
none = "none"

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "tags"

weight = 10

[[footer]]
name = "Categorías"
pageRef = "categories"
weight = 20

[[footer]]
   name = "Autores"
   pageRef = "authors"
   weight = 30