mainSections = ["aboutme", "ai", "blockchain", "geopolitics", "health", "projects", "technology"]
colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
searchIconTitle = "Click to search"
disableImageOptimization = false  # Włącz optymalizację obrazów

# SEO Settings
canonifyURLs = true
enableRobotsTXT = true
disableTextInHeader = false
disableImageZoom = false  # Włącz efekt powiększania Medium Zoom
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultBackgroundImage = "back_optimized.webp"
defaultFeaturedImage = "back_optimized.webp"
highlightCurrentMenuArea = "Enable"
smartTOC = "Enable"
smartTOCHideUnfocusedChildren = "true"
backgroundImageWidth = "1408"
backgroundImageResponsive = true  # Włącz responsywne obrazy
backgroundImageSizes = ["480w", "768w", "1024w", "1280w"]  # Rozmiary dla różnych urządzeń
backgroundImageFormats = ["avif", "webp"]  # Dodajemy obsługę AVIF

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
appearance_switcher = "Switch theme"
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "custom"
showRecent = "Enable"
showRecentItems = "6"
showMoreLink = "Enable"
showMoreLinkDest = "/archives/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = "/images/hero-800.avif"
home_image_blur = false
showOnlyCurrentLang = true

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showAuthorBottom = true
showHero = "Show"
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false
showBreadcrumbs = "Show"
showDraftLabel = true
showEdit = true
editURL = "https://github.com/willhack-g/hugo/tree/main/content"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = "Show"
showTaxonomies = "Show"
showAuthorsBadges = "Show"
showWordCount = true
showZenMode = "Show"
heroStyle = "basic"
showRelatedContent = true
relatedContentLimit = 6
showComments = true
sharingLinks = [ "linkedin", "twitter", "mastodon", "bluesky", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email", "instagram"]

[list]
showHero = true
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]
changefreq = "weekly"
priority = 0.8
filename = "sitemap.xml"

[sitemap.pl]
changefreq = "weekly"
priority = 0.8
filename = "/pl/sitemap.xml"

[sitemap.de]
changefreq = "weekly"
priority = 0.8
filename = "/de/sitemap.xml"

[sitemap.es]
changefreq = "weekly"
priority = 0.8
filename = "/es/sitemap.xml"

[sitemap.zh-cn]
changefreq = "weekly"
priority = 0.8
filename = "/zh-cn/sitemap.xml"

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[analytics]
plausibleAnalytics = true
plausibleDataDomain = "willhack.top"

[verification]

[opengraph]
defaultImage = "def.webp"
imageAlt = "WillHack - Explore the Future of Technology"
defaultImageWidth = "1200"
defaultImageHeight = "630"

[twitter]
handle = "@WillHackLin"
site = "@WillHackLin"
defaultImage = "def.webp"
defaultImageAlt = "WillHack - Explore the Future of Technology"
defaultImageWidth = "1200"
defaultImageHeight = "630"

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]
identifier = "willhack"
enabled = true
globalWidget = true
globalWidgetMessage = ""
globalWidgetColor = "#FFDD0040"
globalWidgetPosition = "left"
showOnArticle = true
widgetScript = "https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js"

[rssnext]

[feed]
title = "WillHack Blog"
description = "WillHack is your comprehensive guide to navigating the future of technology."
favicon = "/favicon.png"
icon = "/favicon.png"
image = "/def.webp"
language = "en"
authorName = "WillHack"
authorEmail = ""
