colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultBackgroundImage = "back.webp"
defaultFeaturedImage = "def.png"
highlightCurrentMenuArea = "Enable"
smartTOC = "Enable"
backgroundImageWidth = "1408"




[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "custom"
showRecent = "enable"
showRecentItems = "6"
#showMoreLink = "Enable"
#showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = "back.webp"
home_image_blur = false
showOnlyCurrentLang = true

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showHero = "Show"
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = true
showBreadcrumbs = "Show"
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = "Show"
showTaxonomies = "Show"
showAuthorsBadges = "Show"
showWordCount = true
showZenMode = "Show"
heroStyle = "basic"
showRelatedContent = false
relatedContentLimit = 6
showComments = true
sharingLinks = [ "linkedin", "twitter", "mastodon", "bluesky", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email"]

[list]
showHero = true
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]
identifier = "WillHack"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD0040"
  globalWidgetPosition = "Left"

[verification]

[rssnext]
